metadataPackage_1628743481622/objects/Institutes__c.object
<CustomObject>
    <label>Institute</label>
    <nameField>
        <label>Institutes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institutes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadataPackage_1628743481622/objects/Mentor__c.object
<CustomObject>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Institute__c</fullName>
        <label>Institute</label>
        <referenceTo>Institutes__c</referenceTo>
        <relationshipLabel>Mentors</relationshipLabel>
        <relationshipName>Mentors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

metadataPackage_1628743481622/objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Mentor__c</fullName>
        <label>Mentor</label>
        <referenceTo>Mentor__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

metadataPackage_1628743481622/classes/sampleInstitute.cls
public class sampleInstitute {
 
    public List<SelectOption>  getMyInstitutes(){
        List<SelectOption> myInst = new List<SelectOption>();
        List<Institutes__c> myList = [SELECT Name,id from Institutes__c]; 
        for (Integer i = 0; i < myList.size(); i++) {
            SelectOption option = new SelectOption(myList[i].id, myList[i].Name);
            myInst.add(option);                      
        }       
        return myInst;
    }

    // public Boolean getBool(){
    //     if(mentId==){
    //         return true;
    //     }
    //     return false;
    // }
    
    public List<Mentor__c> mentors{get; set;}
    public String instId{get; set;}
    public String currInstId{get; set;}
   

    public void getMentors(){

       mentors = [SELECT Name,Designation__c,id from Mentor__c where Institute__c = :instId]; //
    }

    public List<Student__c> students{get; set;}
    public String mentId{get; set;}

    public void  getStudents(){

        students = [SELECT Name,Class__c,City__c,State__c from Student__c where Mentor__c = :mentId ]; 
        
    }
    

}